// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./src/components/BaseHeader/BaseHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LayOut: typeof import('./src/components/LayOut/LayOut.vue')['default']
    LayOutHeader: typeof import('./src/components/LayOut/components/LayOutHeader.vue')['default']
    LayOutLeft: typeof import('./src/components/LayoutLeft/LayOutLeft.vue')['default']
    LayOutLeftMenu: typeof import('./src/components/LayOut/components/LayOutLeftMenu.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NSwitch: typeof import('naive-ui')['NSwitch']
  }
}

export { }
